### ISSUE TITLE
Endpoint not found 

### ISSUE THREAD

**Issue by pyanishjain** [iqans/paytm-checksum-api-nodejs#1]
when i run start  server it gives me Endpoint not found  on webpage
for localhost:3000 and   localhost:3000/paytm

**Comment by iqans** [comment]
The endpoint url is : `http://<url>:<port>/api/v1/paytm/<endpoint>`

Examples:
http://localhost:3000/api/v1/paytm/healthcheck - To verify if API is running correctly
http://localhost:3000/api/v1/paytm/initiatePayment - Will redirect to PayTM gateway for payments
http://localhost:3000/api/v1/paytm/callback - This endpoint is called from PayTM with payload about operation

**Comment by avani17101** [comment]
on http://localhost:3000/api/v1/paytm/healthcheck  I get "Working" 
but on http://localhost:3000/api/v1/paytm/initiatePayment "Something went wrong"
and http://localhost:3000/api/v1/paytm/callback  "Endpoint not found" 
Any idea what is going wrong?
thanks
